# Generated by Django 3.2.9 on 2021-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('third_name', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=2048)),
                ('debt_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_rate', models.DecimalField(decimal_places=0, max_digits=3)),
                ('action_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('S', 'Succes'), ('N', 'None'), ('F', 'Fail')], default='N', max_length=1)),
                ('rate', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green')], default='R', max_length=1)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
