# Generated by Django 3.2.9 on 2021-11-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
